### ISSUE TITLE
missing proto?

### ISSUE THREAD

**Issue by kren1** [ChrisCummins/phd#22]
Hi,

I'm trying to run `artifact_evaluation/03_evaluate_results/run.sh` and I get 
```
mkdir: created directory '/phd/docs/2018-07-issta/artifact_evaluation/03_evaluate_results/output'
Traceback (most recent call last):
  File "/phd/docs/2018-07-issta/artifact_evaluation/03_evaluate_results/experiments.py", line 20, in <module>
    from deeplearning.deepsmith import datastore
  File "/phd/deeplearning/deepsmith/datastore.py", line 10, in <module>
    import deeplearning.deepsmith.client
  File "/phd/deeplearning/deepsmith/client.py", line 2, in <module>
    from deeplearning.deepsmith import db
  File "/phd/deeplearning/deepsmith/db.py", line 12, in <module>
    from deeplearning.deepsmith.proto import datastore_pb2
  File "/phd/deeplearning/deepsmith/proto/datastore_pb2.py", line 25, in <module>
    dependencies=[deeplearning_dot_deepsmith_dot_proto_dot_deepsmith__pb2.DESCRIPTOR,])
  File "/phd/venv/phd/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 829, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "datastore.proto":
  datastore.proto: Import "deeplearning/deepsmith/proto/deepsmith.proto" has not been loaded.
  deepsmith.SubmitTestcasesRequest.testcases: "deepsmith.Testcase" seems to be defined in "deepsmith.proto", which is not imported by "datastore.proto".  To use it here, please add the necessary import.
  deepsmith.RequestTestcasesRequest.testbed: "deepsmith.Testbed" seems to be defined in "deepsmith.proto", which is not imported by "datastore.proto".  To use it here, please add the necessary import.
  deepsmith.RequestTestcasesRequest.harness: "deepsmith.Harness" seems to be defined in "deepsmith.proto", which is not imported by "datastore.proto".  To use it here, please add the necessary import.
  deepsmith.RequestTestcasesResponse.testcases: "deepsmith.Testcase" seems to be defined in "deepsmith.proto", which is not imported by "datastore.proto".  To use it here, please add the necessary import.
  deepsmith.SubmitResultsRequest.results: "deepsmith.Result" seems to be defined in "deepsmith.proto", which is not imported by "datastore.proto".  To use it here, please add the necessary import.
  deepsmith.ResultsCollection.results: "deepsmith.Result" seems to be defined in "deepsmith.proto", which is not imported by "datastore.proto".  To use it here, please add the necessary import.
  deepsmith.ResultsTable.ResultsTableEntry.testbed: "deepsmith.Testbed" seems to be defined in "deepsmith.proto", which is not imported by "datastore.proto".  To use it here, please add the necessary import.
  deepsmith.ResultsTable.ResultsTableEntry.harness: "deepsmith.Harness" seems to be defined in "deepsmith.proto", which is not imported by "datastore.proto".  To use it here, please add the necessary import.
  deepsmith.ResultsTable.ResultsTableEntry.results: "deepsmith.Result" seems to be defined in "deepsmith.proto", which is not imported by "datastore.proto".  To use it here, please add the necessary import.
```

I don't think I know how to solve this one by myself any ideas what might be wrong?

**Comment by ChrisCummins** [comment]
Hi Timotej, thanks for the report. Would you mind reporting the output of:

```
$ head $ROOT/deeplearning/deepsmith/proto/datastore.proto
```

where `$ROOT` is the root directory of this repository (e.g. `~/src/phd`). Could you also please let me know your OS version, and copy and paste the output of:

```
$ $ROOT/docs/2018-07-issta/artifact_evaluation/diagnose_me.sh
```
(again with the `$ROOT` substitute)

Cheers,
Chris

**Comment by kren1** [comment]
Hi Chris,

Thanks for the quick response. I'm using docker with ubuntu base image. 

```
# head /phd/deeplearning/deepsmith/proto/datastore.proto 
syntax = "proto2";
package deepsmith;

import 'deeplearning/deepsmith/proto/deepsmith.proto';

message DataStore {
  message Sqlite {
    optional string path = 1;
    optional bool inmemory = 2 [default = false];
  }
```

diagnose-me.sh outputs:
```
ROOT=/phd
HEAD=d0e20846d98486d7d7b13f682a712d090105184f
Git status:
    On branch master
    Your branch is up-to-date with 'origin/master'.
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)
    
    	modified:   .gitmodules
    	modified:   docs/2018-07-issta/artifact_evaluation/01_evaluate_generator/make_testcases.py
    	modified:   docs/2018-07-issta/artifact_evaluation/01_evaluate_generator/run.sh
    	modified:   docs/2018-07-issta/artifact_evaluation/02_evaluate_harness/experiments.py
    	modified:   docs/2018-07-issta/artifact_evaluation/02_evaluate_harness/run.sh
    	modified:   docs/2018-07-issta/artifact_evaluation/diagnose_me.sh
    
    Untracked files:
      (use "git add <file>..." to include in what will be committed)
    
    	docs/2018-07-issta/artifact_evaluation/.README.txt.swp
    	docs/2018-07-issta/artifact_evaluation/01_evaluate_generator/moutput256/
    	docs/2018-07-issta/artifact_evaluation/02_evaluate_harness/02_evaluate_harness/
    	docs/2018-07-issta/artifact_evaluation/02_evaluate_harness/core
    
    no changes added to commit (use "git add" and/or "git commit -a")
Submodule status:
     77203e5b337489e494a97eb6d4c3d3a05daf56ba deeplearning/clgen (0.4.0-31-g77203e5)
     593f4126fa885898bd93507f28f25df0c88842f0 docs/2016-01-adapt (heads/master)
     fe9715e6105fb87aee3cdf90ecfcab8d6ec6c16a docs/2016-01-hlpgpu (heads/master)
     31db8f130d9b89c87a9bb9df56d0376edb38eef1 docs/2017-02-cgo (heads/master)
     57aa5f5a2ff62768aca3c3b56f197c5fdbac0bc8 docs/2017-09-pact (heads/master)
     16a4db7897c7c600f7b545fff693e0527c7dbcdb experimental/eevee (heads/master)
     da3eadeb6d02daf5be878b6c549abe92bda34c84 experimental/euclid (heads/master)
     1df8341e000dcd75c6577c15d2be0731d46a0150 http/cgo.org/cgo2018 (heads/gh-pages)
     f47e2e87e5574eb0b49dcc3d812065594087ab88 http/chriscummins.cc (f47e2e8)
     81ecbd8ea44610130eb67da2fe0eac1860fa3269 http/humanorrobot.uk (81ecbd8)
     99516d173df15723c58a29f59ed356ec4cec2e14 http/warhaniye.com (heads/gh-pages)
     123007540c2926faf12da48994431aded7ff19e5 learn/interactive-coding-challenges (heads/master)
     bf5d5e05aa0609bcbf9f9b80bb65329d823821e7 system/emu (0.3.0-2-gbf5d5e0)
     6e72b866e0a7fe544b7de2d9951063c9c11c00e3 third_party/torch-rnn (heads/master)
     a0ea1f373c5dca2f55fcde995bf082f9711540bf third_party/visioncpp (heads/master)
     035d954cf86ec2ec53cc269479f1545b55084fe1 util/gh-archiver (0.0.6-2-g035d954)
     cfef05d7915d2c1dacf7630b851154c6149a6666 util/shutterbug (0.0.3-3-gcfef05d)
     18ad2878a05c1967ad610fcbd14fbf2bf13aa82f util/srtime (heads/master)
Repository appears to have been bootstrapped.
Python virtual environment found.
PYTHON=/phd/venv/phd/bin/python
PYTHONPATH=/phd/tools/../:/phd/tools/..//lib:/phd/tools/..//bazel-genfiles
PYTHON_VERSION=Python 3.6.5
Python packages:
    You are using pip version 9.0.3, however version 10.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    absl-py==0.1.10
    appdirs==1.4.3
    appnope==0.1.0
    astroid==1.6.1
    attrs==17.4.0
    autoenv==1.0.0
    bleach==2.1.3
    certifi==2018.4.16
    cffi==1.11.5
    chardet==3.0.4
    checksumdir==1.0.5
    CLgen==0.4.0.dev0
    coverage==4.5.1
    cycler==0.10.0
    decorator==4.2.1
    editdistance==0.3.1
    entrypoints==0.2.3
    grpcio==1.10.0
    grpcio-tools==1.10.0
    html5lib==1.0.1
    humanize==0.5.1
    idna==2.6
    ipykernel==4.8.2
    ipython==6.2.1
    ipython-genutils==0.2.0
    ipywidgets==7.1.2
    isort==4.3.4
    jedi==0.11.1
    Jinja2==2.10
    jsonschema==2.6.0
    jupyter==1.0.0
    jupyter-client==5.2.2
    jupyter-console==5.2.0
    jupyter-core==4.4.0
    kiwisolver==1.0.1
    labm8==0.1.2
    lazy-object-proxy==1.3.1
    MarkupSafe==1.0
    matplotlib==2.2.0rc1
    mccabe==0.6.1
    mistune==0.8.3
    mysqlclient==1.3.12
    nbconvert==5.3.1
    nbformat==4.4.0
    notebook==5.4.0
    numpy==1.14.1
    pandas==0.22.0
    pandocfilters==1.4.2
    parso==0.1.1
    pexpect==4.4.0
    pickleshare==0.7.4
    pluggy==0.6.0
    ply==3.11
    prettytable==0.7.2
    progressbar2==3.37.1
    prompt-toolkit==1.0.15
    protobuf==3.5.1
    psutil==5.4.5
    psycopg2-binary==2.7.4
    ptyprocess==0.5.2
    py==1.5.2
    py-cpuinfo==3.3.0
    pycparser==2.17
    pycparserext==2016.2
    PyGithub==1.29
    Pygments==2.2.0
    pylint==1.8.2
    pyopencl==2018.1.1
    pyparsing==2.2.0
    pytest==3.4.1
    pytest-cov==2.5.1
    python-dateutil==2.6.1
    python-utils==2.3.0
    pytools==2018.1
    pytz==2018.3
    pyzmq==17.0.0
    qtconsole==4.3.1
    requests==2.18.4
    scipy==1.1.0
    Send2Trash==1.5.0
    simplegeneric==0.8.1
    six==1.11.0
    SQLAlchemy==1.2.7
    tensorflow==1.0.0
    terminado==0.8.1
    testpath==0.3.1
    tornado==5.0
    traitlets==4.3.2
    urllib3==1.22
    wcwidth==0.1.7
    webencodings==0.5.1
    widgetsnbextension==3.1.4
    wrapt==1.10.11
Python protocol buffer code is generated.
CLGEN=/phd/venv/phd/bin/clgen

Available OpenCL devices:
    1+-:  Device: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, Platform: Intel(R) OpenCL
```

**Comment by ChrisCummins** [comment]
Hm interesting. I'm unable to re-produce on my machine, so I'll grab a docker image and try to make a fix. In the meantime, here's a workaround for you:

Replace the contents of the file `deeplearning/deepsmith/proto/datastore.proto` with this:

```proto
syntax = "proto2";
package deepsmith;

message ProfilingEvent {
  // A unique client name. A good starting point would be the hostname.
  optional string client = 1;

  // The type of profiling event. E.g. "overhead", "generation", "warmup", etc.
  optional string type = 2;

  // The duration of the event, expressed in milliseconds.
  optional int64 duration_ms = 3;

  // The start of the profiling event, expressed in milliseconds since the
  // epoch.
  optional int64 event_start_epoch_ms = 4;
}

message Testcase {
  optional string toolchain = 1;
  optional Generator generator = 2;
  optional Harness harness = 3;

  // <input_name, input_value>
  map<string, string> inputs = 4;

  map<string, string> invariant_opts = 5;

  repeated ProfilingEvent profiling_events = 6;
}

message Generator {
  optional string name = 1;
  map<string, string> opts = 2;
}

message Harness {
  optional string name = 1;
  map<string, string> opts = 2;
}

message Testbed {
  optional string toolchain = 1;
  optional string name = 2;
  map<string, string> opts = 3;
}

message Result {
  optional Testcase testcase = 1;
  optional Testbed testbed = 2;
  optional int32 returncode = 3;
  // <name, value>
  map<string, string> outputs = 4;
  repeated ProfilingEvent profiling_events = 5;
}


message DataStore {
  message Sqlite {
    optional string path = 1;
    optional bool inmemory = 2 [default = false];
  }

  message MySql {
    optional string database = 1;
    optional string hostname = 2 [default = "localhost"];
    optional int32 port = 3 [default = 3306];
    optional string username = 4;
    optional string password = 5;
  }

  message PostgreSql {
    optional string database = 1;
    optional string hostname = 2 [default = "localhost"];
    optional int32 port = 3 [default = 5432];
    optional string username = 4;
    optional string password = 5;
  }

  oneof backend {
    Sqlite sqlite = 1;
    MySql mysql = 2;
    PostgreSql postgresql = 3;
  }

  optional bool create_database_if_not_exist = 100;

  // Mark this datastore as _only_ for testing.
  optional bool testonly = 101;
}

// A map of datastore names to configs.
//
// Used by //deeplearning/deepsmith:conftest to parameterize the test fixtures
// used for unit tests.
message DataStoreTestSet {
  map<string, DataStore> values = 1;
}

//
// RPCs
//

// SubmitTestcases

message SubmitTestcasesRequest {
  // Reserved for later use as ID field.
  reserved 1;

  optional string client = 2 [default = "<anon>"];
  repeated Testcase testcases = 3;
}

message SubmitTestcasesResponse {
  enum Status {
    SUCCESS = 0;
    FAILURE = 1;
  }

  optional Status status = 1 [default = SUCCESS];
  optional string server_name = 2;
  optional int32 error_code = 3;
  optional int32 num_truncated_outputs = 4;
}

// RequestTestcases.

message RequestTestcasesRequest {
  // The client name, e.g. $HOSTNAME.
  optional string client = 1 [default = "<anon>"];

  optional string toolchain = 9;
  optional Testbed testbed = 2;
  optional Harness harness = 3;

  optional bool return_testcases = 5 [default = true];
  optional bool mark_pending_results = 6 [default = true];

  // Must be >= 1.
  optional int32 max_num_testcases = 4 [default = 100];

  optional bool include_testcases_with_results = 100 [default = false];
  optional bool include_testcases_with_pending_results = 101 [default = false];
  optional bool return_total_matching_count = 102 [default = false];
}

message RequestTestcasesResponse {
  enum Status {
    SUCCESS = 0;
    FAILURE = 1;
    INVALID_REQUEST = 2;
  }

  optional Status status = 1 [default = SUCCESS];
  optional string server_name = 2;
  repeated Testcase testcases = 4;

  optional int64 total_matching_count = 5;

  // Only set if status != SUCCESS.
  optional string error = 6;
}

// SubmitTestcases

message SubmitResultsRequest {
  // Reserved for later use as ID field.
  reserved 1;

  // TODO(cec): Normalize results using repeated fields and indices.
  repeated Result results = 2;
}

message SubmitResultsResponse {
  enum Status {
    SUCCESS = 0;
    FAILURE = 1;
  }

  optional Status status = 1 [default = SUCCESS];
}

// Service.

service TestingService {
  rpc SubmitTestcases (SubmitTestcasesRequest) returns (SubmitTestcasesResponse);
  rpc RequestTestCases (RequestTestcasesRequest) returns (RequestTestcasesResponse);
  rpc SubmitResults (SubmitResultsRequest) returns (SubmitResultsResponse);
}


message ResultsCollection {
  // Reserved for later use as ID field.
  reserved 1;

  repeated Result results = 2;
}

message ResultsTable {
  message ResultsTableEntry {
    optional Testbed testbed = 1;
    optional Harness harness = 2;
    // Result.testcase must be none.
    repeated Result results = 3;
  }

  // Reserved for later use as ID field.
  reserved 1;

  repeated ResultsTableEntry entries = 2;
}
```

Then, from the root directory of this repository, run:

```
$ source .env
$ ./tools/protoc.sh
```

That should "fix" the problem and allow you to run the third artifact eval script. Let me know if you have any problems :)

**Comment by kren1** [comment]
Building from plain docker image isn't straightforward, had to tinker around a bit to make it work (atleast the first 2 stages), so I'm not sure how well you can reproduce. 

I did what you said and this gives me another error:

```
Traceback (most recent call last):
  File "/phd/docs/2018-07-issta/artifact_evaluation/03_evaluate_results/experiments.py", line 20, in <module>
    from deeplearning.deepsmith import datastore
  File "/phd/deeplearning/deepsmith/datastore.py", line 11, in <module>
    import deeplearning.deepsmith.generator
  File "/phd/deeplearning/deepsmith/generator.py", line 12, in <module>
    from deeplearning.deepsmith.proto import deepsmith_pb2
  File "/phd/deeplearning/deepsmith/proto/deepsmith_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x0f\x64\x65\x65psmith.proto\x12\tdeepsmith\"a\n\x0eProfilingEvent\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03\x12\x1c\n\x14\x65vent_start_epoch_ms\x18\x04 \x01(\x03\"\xf6\x02\n\x08Testcase\x12\x11\n\ttoolchain\x18\x01 \x01(\t\x12\'\n\tgenerator\x18\x02 \x01(\x0b\x32\x14.deepsmith.Generator\x12#\n\x07harness\x18\x03 \x01(\x0b\x32\x12.deepsmith.Harness\x12/\n\x06inputs\x18\x04 \x03(\x0b\x32\x1f.deepsmith.Testcase.InputsEntry\x12>\n\x0einvariant_opts\x18\x05 \x03(\x0b\x32&.deepsmith.Testcase.InvariantOptsEntry\x12\x33\n\x10profiling_events\x18\x06 \x03(\x0b\x32\x19.deepsmith.ProfilingEvent\x1a-\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x34\n\x12InvariantOptsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"t\n\tGenerator\x12\x0c\n\x04name\x18\x01 \x01(\t\x12,\n\x04opts\x18\x02 \x03(\x0b\x32\x1e.deepsmith.Generator.OptsEntry\x1a+\n\tOptsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"p\n\x07Harness\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x04opts\x18\x02 \x03(\x0b\x32\x1c.deepsmith.Harness.OptsEntry\x1a+\n\tOptsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x83\x01\n\x07Testbed\x12\x11\n\ttoolchain\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\x04opts\x18\x03 \x03(\x0b\x32\x1c.deepsmith.Testbed.OptsEntry\x1a+\n\tOptsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xfe\x01\n\x06Result\x12%\n\x08testcase\x18\x01 \x01(\x0b\x32\x13.deepsmith.Testcase\x12#\n\x07testbed\x18\x02 \x01(\x0b\x32\x12.deepsmith.Testbed\x12\x12\n\nreturncode\x18\x03 \x01(\x05\x12/\n\x07outputs\x18\x04 \x03(\x0b\x32\x1e.deepsmith.Result.OutputsEntry\x12\x33\n\x10profiling_events\x18\x05 \x03(\x0b\x32\x19.deepsmith.ProfilingEvent\x1a.\n\x0cOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01')
  File "/phd/venv/phd/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 829, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "deepsmith.proto":
  deepsmith.ProfilingEvent.client: "deepsmith.ProfilingEvent.client" is already defined in file "datastore.proto".
  deepsmith.ProfilingEvent.type: "deepsmith.ProfilingEvent.type" is already defined in file "datastore.proto".
  deepsmith.ProfilingEvent.duration_ms: "deepsmith.ProfilingEvent.duration_ms" is already defined in file "datastore.proto".
  deepsmith.ProfilingEvent.event_start_epoch_ms: "deepsmith.ProfilingEvent.event_start_epoch_ms" is already defined in file "datastore.proto".
  deepsmith.ProfilingEvent: "deepsmith.ProfilingEvent" is already defined in file "datastore.proto".
  deepsmith.Testcase.toolchain: "deepsmith.Testcase.toolchain" is already defined in file "datastore.proto".
  deepsmith.Testcase.generator: "deepsmith.Testcase.generator" is already defined in file "datastore.proto".
  deepsmith.Testcase.harness: "deepsmith.Testcase.harness" is already defined in file "datastore.proto".
  deepsmith.Testcase.inputs: "deepsmith.Testcase.inputs" is already defined in file "datastore.proto".
  deepsmith.Testcase.invariant_opts: "deepsmith.Testcase.invariant_opts" is already defined in file "datastore.proto".
  deepsmith.Testcase.profiling_events: "deepsmith.Testcase.profiling_events" is already defined in file "datastore.proto".
  deepsmith.Testcase.InputsEntry.key: "deepsmith.Testcase.InputsEntry.key" is already defined in file "datastore.proto".
  deepsmith.Testcase.InputsEntry.value: "deepsmith.Testcase.InputsEntry.value" is already defined in file "datastore.proto".
  deepsmith.Testcase.InputsEntry: "deepsmith.Testcase.InputsEntry" is already defined in file "datastore.proto".
  deepsmith.Testcase.InvariantOptsEntry.key: "deepsmith.Testcase.InvariantOptsEntry.key" is already defined in file "datastore.proto".
  deepsmith.Testcase.InvariantOptsEntry.value: "deepsmith.Testcase.InvariantOptsEntry.value" is already defined in file "datastore.proto".
  deepsmith.Testcase.InvariantOptsEntry: "deepsmith.Testcase.InvariantOptsEntry" is already defined in file "datastore.proto".
  deepsmith.Testcase: "deepsmith.Testcase" is already defined in file "datastore.proto".
  deepsmith.Generator.name: "deepsmith.Generator.name" is already defined in file "datastore.proto".
  deepsmith.Generator.opts: "deepsmith.Generator.opts" is already defined in file "datastore.proto".
  deepsmith.Generator.OptsEntry.key: "deepsmith.Generator.OptsEntry.key" is already defined in file "datastore.proto".
  deepsmith.Generator.OptsEntry.value: "deepsmith.Generator.OptsEntry.value" is already defined in file "datastore.proto".
  deepsmith.Generator.OptsEntry: "deepsmith.Generator.OptsEntry" is already defined in file "datastore.proto".
  deepsmith.Generator: "deepsmith.Generator" is already defined in file "datastore.proto".
  deepsmith.Harness.name: "deepsmith.Harness.name" is already defined in file "datastore.proto".
  deepsmith.Harness.opts: "deepsmith.Harness.opts" is already defined in file "datastore.proto".
  deepsmith.Harness.OptsEntry.key: "deepsmith.Harness.OptsEntry.key" is already defined in file "datastore.proto".
  deepsmith.Harness.OptsEntry.value: "deepsmith.Harness.OptsEntry.value" is already defined in file "datastore.proto".
  deepsmith.Harness.OptsEntry: "deepsmith.Harness.OptsEntry" is already defined in file "datastore.proto".
  deepsmith.Harness: "deepsmith.Harness" is already defined in file "datastore.proto".
  deepsmith.Testbed.toolchain: "deepsmith.Testbed.toolchain" is already defined in file "datastore.proto".
  deepsmith.Testbed.name: "deepsmith.Testbed.name" is already defined in file "datastore.proto".
  deepsmith.Testbed.opts: "deepsmith.Testbed.opts" is already defined in file "datastore.proto".
  deepsmith.Testbed.OptsEntry.key: "deepsmith.Testbed.OptsEntry.key" is already defined in file "datastore.proto".
  deepsmith.Testbed.OptsEntry.value: "deepsmith.Testbed.OptsEntry.value" is already defined in file "datastore.proto".
  deepsmith.Testbed.OptsEntry: "deepsmith.Testbed.OptsEntry" is already defined in file "datastore.proto".
  deepsmith.Testbed: "deepsmith.Testbed" is already defined in file "datastore.proto".
  deepsmith.Result.testcase: "deepsmith.Result.testcase" is already defined in file "datastore.proto".
  deepsmith.Result.testbed: "deepsmith.Result.testbed" is already defined in file "datastore.proto".
  deepsmith.Result.returncode: "deepsmith.Result.returncode" is already defined in file "datastore.proto".
  deepsmith.Result.outputs: "deepsmith.Result.outputs" is already defined in file "datastore.proto".
  deepsmith.Result.profiling_events: "deepsmith.Result.profiling_events" is already defined in file "datastore.proto".
  deepsmith.Result.OutputsEntry.key: "deepsmith.Result.OutputsEntry.key" is already defined in file "datastore.proto".
  deepsmith.Result.OutputsEntry.value: "deepsmith.Result.OutputsEntry.value" is already defined in file "datastore.proto".
  deepsmith.Result.OutputsEntry: "deepsmith.Result.OutputsEntry" is already defined in file "datastore.proto".
  deepsmith.Result: "deepsmith.Result" is already defined in file "datastore.proto".
  deepsmith.Testcase.generator: "deepsmith.Generator" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Testcase.harness: "deepsmith.Harness" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Testcase.inputs: "deepsmith.Testcase.InputsEntry" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Testcase.invariant_opts: "deepsmith.Testcase.InvariantOptsEntry" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Testcase.profiling_events: "deepsmith.ProfilingEvent" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Generator.opts: "deepsmith.Generator.OptsEntry" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Harness.opts: "deepsmith.Harness.OptsEntry" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Testbed.opts: "deepsmith.Testbed.OptsEntry" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Result.testcase: "deepsmith.Testcase" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Result.testbed: "deepsmith.Testbed" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Result.outputs: "deepsmith.Result.OutputsEntry" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.
  deepsmith.Result.profiling_events: "deepsmith.ProfilingEvent" seems to be defined in "datastore.proto", which is not imported by "deepsmith.proto".  To use it here, please add the necessary import.

```

**Comment by ChrisCummins** [comment]
Great! I admit I haven't used Docker before, I assumed that like with previous VM/containers I've looked at it wouldn't allow access to GPUs for OpenCL. It looks like this restriction doesn't apply (at least on Linux), so I'm going to prepare a Dockerfile for this repo. Are there any hacks you found necessary to build with Docker?

Cheers,
Chris

**Comment by kren1** [comment]
Nice! Docker would indeed be very helpful. I actually used `pkienzle/opencl_docker` as the base image, which took away most of the OpenCL headaches for me. I don't remeber every problem I encountered, but here's a few in found in my bash history:

* pyopencl wouldn't install so I had to use `CFLAGS=-L/opt/intel/opencl-1.2-6.4.0.25/lib64/ pip install pyopencl`
*  Then there was an issue with python3.6 and importinging `distuils`, which was handled by `apt install python3-distutils`
* There was a missing locale issue, so I had to use 
```
export LC_ALL="en_GB.UTF-8"
dpkg-reconfigure locales
```

Also the docker image gets to 14GB, so would be nice to slim it down a bit.

Cheers,
Timotej

**Comment by ChrisCummins** [comment]
Brilliant, thanks for the pointers Timotej. I've added a [Dockerfile](https://github.com/ChrisCummins/phd/blob/master/docs/2018_07_issta/artifact_evaluation/Dockerfile) and [instructions](https://github.com/ChrisCummins/phd/tree/master/docs/2018_07_issta/artifact_evaluation#21-docker-container). One caveat is the enormous final image size, due to each command in the Dockerfile creating a new image. I'm working on a fix for this, probably using the experimental `--squash` feature, or just concatting all the `RUN` commands into a single script.

Cheers,
Chris
