### ISSUE TITLE
Got An Error on ‘docker run chriscummins/opencl_fuzz’

### ISSUE THREAD

**Issue by Implementist** [ChrisCummins/phd#25]
Hi，Mr.Cummins
When I try to do `docker run chriscummins/opencl_fuzz` I got an error like:
`I0728 03:12:19.383133 140557201053440 opencl_fuzz.py:331] Recording interesting results in /out.
I0728 03:12:19.383535 140557201053440 opencl_fuzz.py:333] Preparing generator.
Traceback (most recent call last):
  File "/app/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz_image.binary.runfiles/phd/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz.py", line 373, in <module>
    app.run(main)
  File "/app/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz_image.binary.runfiles/pypi__absl_py_0_1_10/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/app/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz_image.binary.runfiles/pypi__absl_py_0_1_10/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/app/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz_image.binary.runfiles/phd/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz.py", line 336, in main
    clgen_pretrained.ClgenGenerator)
  File "/app/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz_image.binary.runfiles/phd/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz.py", line 311, in GeneratorFromFlag
    return generator_class(config)
  File "/app/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz_image.binary.runfiles/phd/deeplearning/deepsmith/generators/clgen_pretrained.py", line 53, in __init__
    self.instance = sample.Instance(self.config.instance)
  File "/app/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz_image.binary.runfiles/phd/deeplearning/clgen/sample.py", line 46, in __init__
    pathlib.Path(config.pretrained_model))
  File "/app/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz_image.binary.runfiles/phd/deeplearning/clgen/models/pretrained.py", line 31, in __init__
    self.cache = cache.FSCache(self.path)
AttributeError: module 'deeplearning.clgen.cache' has no attribute 'FSCache'`

How can I fix this?

**Comment by ChrisCummins** [comment]
Hi @Implementist , thanks for the bug report! I see the root cause and will push a fix shortly. In the mean time, could you help me reproduce the issue - what operating system are you using, and which version of docker?

Cheers,
Chris

**Comment by Implementist** [comment]
Hi Mr.Cummins,
Today I tried that command on another Server with Ubuntu 16.04 and docker '18.06.0-ce, build 0ffa825'. And I got the same error.

**Comment by ChrisCummins** [comment]
Hi @Implementist , thanks for the further details. Confusingly, I have been unable to reproduce the error on any of my machines (I'm no Docker expert so maybe I'm making a simple mistake, but I thought the advantage of containerized apps is that it makes these sorts of problems reproducible on any system?).

Nevertheless, I have pushed a new docker image which contains an (untested) fix, `sha256:ef58b41d0a63e79923bb7bc0bb834cb397ae9a05e7bcc9fa2122af9f5a303ce2`.

If you update your image with `docker pull chriscummins/opencl_fuzz` the problem should go away.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Hi @Implementist, were you able to test my fix for this issue?
