### ISSUE TITLE
//deeplearning/clgen default sample crashes in new docker container

### ISSUE THREAD

**Issue by BeauJoh** [ChrisCummins/phd#27]
Hi  @ChrisCummins,

I've followed the instructions in the wiki for clgen in a new docker container, installed the dependencies and bazel.

`bazel build //deeplearning/clgen` compiles ok, but when I run `bazel-out/*-py3-opt/bin/deeplearning/clgen/clgen     --config deeplearning/clgen/test/data/tiny/config.pbtxt`

I first get an encoding error 

```
File "/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/phd/deeplearning/clgen/clgen.py", line 15
SyntaxError: Non-ASCII character '\xe2' in file /phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/phd/deeplearning/clgen/clgen.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

which I can correct by putting a `# -*- coding: utf-8 -*-` at the start of `deeplearning/clgen/clgen.py` but then I get errors at:

```
File "/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/phd/deeplearning/clgen/clgen.
py", line 96
    self.working_dir: pathlib.Path = pathlib.Path(
                    ^
SyntaxError: invalid syntax

```

Am I forgetting to set an environment variable, or am I missing something with this build process? Sorry, I've not used basel before, but thought you might be able to quickly point me in the right direction...

Beau.

**Comment by ChrisCummins** [comment]
Hey Beau, sorry I'm still ironing out a bunch of issues in the new build system, and bazel support for python3 is really patchy. Thanks for the bug report :) Those errors look like bazel is using an old python version (all my code requires >= 3.6). Could you try forcing the default python to 3.6 and see if that fixes it? Maybe something like:

```
$ mkdir -p ~/.local/bin
$ export PATH=$HOME/.local/bin:$PATH
$ ln -s $(which python3.6) ~/.local/bin/python
$ python --version
# Confirm that it returns something like Python 3.6.5
```

Cheers,
Chris

**Comment by BeauJoh** [comment]
No wuckaz, aside from the kinks the bazel build process with docker looks really cool.

Ok, now we're getting somewhere! Forcing the version of Python to 3.6.5 gives us:

```
root@ebaef196fbd6:/phd# bazel-out/*-py3-opt/bin/deeplearning/clgen/clgen \
>     --config deeplearning/clgen/test/data/tiny/config.pbtxt
Traceback (most recent call last):
  File "/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/phd/deeplearning/clgen/clgen.
py", line 18, in <module>
    import cProfile
  File "/usr/lib/python3.6/cProfile.py", line 10, in <module>
    import profile as _pyprofile
  File "/usr/lib/python3.6/profile.py", line 31, in <module>
    from optparse import OptionParser
  File "/usr/lib/python3.6/optparse.py", line 77, in <module>
    import textwrap
  File "/usr/lib/python3.6/textwrap.py", line 8, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

Have you seen that before?

**Comment by ChrisCummins** [comment]
We're getting there!

I traced your steps and managed to reproduce the problem. It seems I missed some of the python3 compatibility workaround steps from the build docs. I've updated the instructions so it'll work for a fresh docker image.

From your current docker image, I believe you can patch things up using:

```sh
$ sudo apt install -y --no-install-recommends \
   ca-certificates curl g++ git libmysqlclient-dev ocl-icd-opencl-dev \
   pkg-config python python-dev python3.6 python3.6-dev python3-distutils \
   unzip zip zlib1g-dev openjdk-11-jdk
$ source /phd/.env
```

Then to be on the safe side, run a clean build using:

```sh
$ bazel clean --expunge && rm -rf ~/.local/cache/bazel/*
$ bazel run //deeplearning/clgen -- --config /phd/deeplearning/clgen/tests/data/tiny/config.pbtxt
```

Cheers,
Chris

**Comment by BeauJoh** [comment]
Ok, we're getting there.

After your suggestions I received:

```
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/ce788644d82188e468bbfba809395ca6/execroot/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/phd/deeplearning/clgen/clgen.py", line 33, in <module>
    from deeplearning.clgen.models import models
  File "/root/.cache/bazel/_bazel_root/ce788644d82188e468bbfba809395ca6/execroot/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/phd/deeplearning/clgen/models/models.py", line 20, in <module>
    from deeplearning.clgen.corpuses import corpuses
  File "/root/.cache/bazel/_bazel_root/ce788644d82188e468bbfba809395ca6/execroot/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/phd/deeplearning/clgen/corpuses/corpuses.py", line 21, in <module>
    from deeplearning.clgen.corpuses import encoded
  File "/root/.cache/bazel/_bazel_root/ce788644d82188e468bbfba809395ca6/execroot/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/phd/deeplearning/clgen/corpuses/encoded.py", line 12, in <module>
    import progressbar
  File "/root/.cache/bazel/_bazel_root/ce788644d82188e468bbfba809395ca6/execroot/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/pypi__progressbar2_3_37_1/progressbar/__init__.py", line 3, in <module>
    from .utils import streams
  File "/root/.cache/bazel/_bazel_root/ce788644d82188e468bbfba809395ca6/execroot/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/pypi__progressbar2_3_37_1/progressbar/utils.py", line 6, in <module>
    from python_utils.time import timedelta_to_seconds, epoch, format_time
ModuleNotFoundError: No module named 'python_utils'

```

Which I fixed by adding `python_utils==2.3.0` to requirements.txt

Additionally, I rolled back the version of bleach and html5lib since they are dependencies of tensorboard. So the versions were changed to:

`bleach-1.5.0 html5lib-0.9999999 python-utils-2.3.0`

Since I'm not sure where requirements.txt is evaluated in bazel, I installed pip and the dependencies with:

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python ./get-pip.py
pip install -r requirements.txt

```

Next, I followed your steps and:

```
bazel clean --expunge && rm -rf ~/.local/cache/bazel/*
./configure --with_cuda --update_git_submodules --symlink_python --noninteractive
 bazel run //deeplearning/clgen -- --config /phd/deeplearning/clgen/tests/data/tiny/config.pbtxt

```

So at least we're building now! Unfortunately, I'm missing the cuda runtime for pytorch.

```
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

```

I've changed the docker image to nvidia/cuda, in particular:

`sudo docker run --runtime=nvidia -it --rm nvidia/cuda:9.2-runtime-ubuntu18.04 /bin/bash`

which features `/usr/local/cuda/lib64/libcublas.so.9.2`

Unfortunately, I still can't fix: `ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory`. I've tried symlinking and setting LD_LIBRARY_PATH, but neither have any effect.
Apparently -- it's mentioned (here)[https://github.com/tensorflow/tensorflow/issues/15604] the latest version of tensorflow is still using Cuda 9.0, but the nvidia/cuda 18.04 release of Ubuntu docker container is only supported for Cuda 9.2, so changing the image isn't an option.

I've added a directory -- to my fork of this repo -- with a dockerfile to help reproduce the problem.
Could you run the following and tell me where you get to? I don't really know how tensorflow is installed in the bazel project and thought maybe you'd be able to solve this faster?

`docker build -t clgen-instance https://raw.githubusercontent.com/BeauJoh/phd/master/docker-builds/Dockerfile`

Beau.

**Comment by BeauJoh** [comment]
Thanks for getting on this so quickly, it works a charm and no worries with the testing.
I think removing tensorboard from the dependencies was an accident, it probably occurred when I was trying to compile a few days ago.
After we met at the ECOOP/ISTA poster session I've been keen to test my predictive models with your synthesized kernel generation. I'll let you know how I get on!

Beau.

**Comment by JiajieZhang-Georgia** [comment]
> No wuckaz, aside from the kinks, the bazel build process with docker looks really cool.
> 
> Ok, now we're getting somewhere! Forcing the version of Python to 3.6.5 gives us:
> 
> ```
> root@ebaef196fbd6:/phd# bazel-out/*-py3-opt/bin/deeplearning/clgen/clgen \
> >     --config deeplearning/clgen/test/data/tiny/config.pbtxt
> Traceback (most recent call last):
>   File "/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/clgen.runfiles/phd/deeplearning/clgen/clgen.
> py", line 18, in <module>
>     import cProfile
>   File "/usr/lib/python3.6/cProfile.py", line 10, in <module>
>     import profile as _pyprofile
>   File "/usr/lib/python3.6/profile.py", line 31, in <module>
>     from optparse import OptionParser
>   File "/usr/lib/python3.6/optparse.py", line 77, in <module>
>     import textwrap
>   File "/usr/lib/python3.6/textwrap.py", line 8, in <module>
>     import re
>   File "/usr/lib/python3.6/re.py", line 142, in <module>
>     class RegexFlag(enum.IntFlag):
> AttributeError: module 'enum' has no attribute 'IntFlag'
> ```
> Have you seen that before?

Hi BeauJoh @BeauJoh 
Could you please tell me how to solve the problem of 'AttributeError: module 'enum' has no attribute 'IntFlag''

I went through your questions and answers, but still don't know how to fix it.
Thank you.
