### ISSUE TITLE
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@org_pubref_rules_protobuf' (requested by nodes 'REPOSITORY:@org_pubref_rules_protobuf')

### ISSUE THREAD

**Issue by luojuan5** [ChrisCummins/phd#32]
Hi，Mr.Cummins:
       When I install the environment according to the README.md file in the phd directory, I execute bazel test //... or bazel test //lib/labm8:fs_test,error is as follows：

Starting local Bazel server and connecting to it...
...........
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@org_pubref_rules_protobuf' (requested by nodes 'REPOSITORY:@org_pubref_rules_protobuf')
INFO: Elapsed time: 0.639s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@org_pubref_rules_protobuf' (requested by nodes 'REPOSITORY:@org_pubref_rules_protobuf')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:441)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Integer value http.postBuffer out of range
	at org.eclipse.jgit.lib.DefaultTypedConfigGetter.getInt(DefaultTypedConfigGetter.java:153)
	at org.eclipse.jgit.lib.Config.getInt(Config.java:263)
	at org.eclipse.jgit.transport.HttpConfig.init(HttpConfig.java:229)
	at org.eclipse.jgit.transport.HttpConfig.<init>(HttpConfig.java:202)
	at org.eclipse.jgit.transport.TransportHttp.<init>(TransportHttp.java:280)
	at org.eclipse.jgit.transport.TransportHttp$1.open(TransportHttp.java:207)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:570)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:446)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:325)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:294)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:228)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
	at com.google.devtools.build.lib.bazel.repository.GitCloner.clone(GitCloner.java:199)
	at com.google.devtools.build.lib.bazel.repository.GitRepositoryFunction.fetch(GitRepositoryFunction.java:73)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:188)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:363)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@org_pubref_rules_protobuf' (requested by nodes 'REPOSITORY:@org_pubref_rules_protobuf')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:441)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Integer value http.postBuffer out of range
	at org.eclipse.jgit.lib.DefaultTypedConfigGetter.getInt(DefaultTypedConfigGetter.java:153)
	at org.eclipse.jgit.lib.Config.getInt(Config.java:263)
	at org.eclipse.jgit.transport.HttpConfig.init(HttpConfig.java:229)
	at org.eclipse.jgit.transport.HttpConfig.<init>(HttpConfig.java:202)
	at org.eclipse.jgit.transport.TransportHttp.<init>(TransportHttp.java:280)
	at org.eclipse.jgit.transport.TransportHttp$1.open(TransportHttp.java:207)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:570)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:446)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:325)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:294)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:228)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
	at com.google.devtools.build.lib.bazel.repository.GitCloner.clone(GitCloner.java:199)
	at com.google.devtools.build.lib.bazel.repository.GitRepositoryFunction.fetch(GitRepositoryFunction.java:73)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:188)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:363)
FAILED: Build did NOT complete successfully (0 packages loaded)

Could you give me some help? Thank you!

**Comment by luojuan5** [comment]
I have solved this problem today. Thank you any way

**Comment by ChrisCummins** [comment]
Thanks for the update. Would you mind posting what the fix was? I can update the docs accordingly.

**Comment by ChrisCummins** [comment]
Hm that's a new one to me! Thanks for letting us know

**Comment by luojuan5** [comment]
> Hm that's a new one to me! Thanks for letting us know

You are welcome. ^_^
